Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
document = readDoc("berita1.txt")
sentences_list = tokenize(document)
------------------

[0;31m[0m
[0;31mFileNotFoundError[0mTraceback (most recent call last)
[0;32m<ipython-input-4-2c4580d040e7>[0m in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0;31m [0mdocument[0m [0;34m=[0m [0mreadDoc[0m[0;34m([0m[0;34m"berita1.txt"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0msentences_list[0m [0;34m=[0m [0mtokenize[0m[0;34m([0m[0mdocument[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m<ipython-input-2-d819197fba38>[0m in [0;36mreadDoc[0;34m(name)[0m
[1;32m     15[0m [0;34m[0m[0m
[1;32m     16[0m     [0;32mif[0m [0mchoice[0m [0;34m==[0m [0;36m1[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 17[0;31m         [0mf[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0mname[0m[0;34m,[0m [0;34m'r'[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0;34m"utf8"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     18[0m         [0mdocument[0m [0;34m=[0m [0mf[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     19[0m         [0mf[0m[0;34m.[0m[0mclose[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'berita1.txt'
FileNotFoundError: [Errno 2] No such file or directory: 'berita1.txt'

